/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmgpupropagator_free: (a: number, b: number) => void;
export const __wbg_wasmpropagator_free: (a: number, b: number) => void;
export const wasmgpupropagator_getHeight: (a: number) => number;
export const wasmgpupropagator_getState: (a: number) => [number, number, number];
export const wasmgpupropagator_getStats: (a: number) => [number, number, number];
export const wasmgpupropagator_getStep: (a: number) => bigint;
export const wasmgpupropagator_getTime: (a: number) => number;
export const wasmgpupropagator_getWidth: (a: number) => number;
export const wasmgpupropagator_new: (a: number, b: number, c: number, d: number) => any;
export const wasmgpupropagator_reset: (a: number, b: number, c: number) => [number, number];
export const wasmgpupropagator_run: (a: number, b: bigint) => any;
export const wasmgpupropagator_step: (a: number) => any;
export const wasmgpupropagator_totalMass: (a: number) => number;
export const wasmpropagator_getHeight: (a: number) => number;
export const wasmpropagator_getState: (a: number) => [number, number, number];
export const wasmpropagator_getStats: (a: number) => [number, number, number];
export const wasmpropagator_getStep: (a: number) => bigint;
export const wasmpropagator_getTime: (a: number) => number;
export const wasmpropagator_getWidth: (a: number) => number;
export const wasmpropagator_new: (a: number, b: number, c: number, d: number) => [number, number, number];
export const wasmpropagator_reset: (a: number, b: number, c: number) => [number, number];
export const wasmpropagator_run: (a: number, b: bigint) => void;
export const wasmpropagator_step: (a: number) => void;
export const wasmpropagator_totalMass: (a: number) => number;
export const init: () => void;
export const wasm_bindgen__convert__closures_____invoke__h79f9d13035c10189: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__hf6a99b71828d481c: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hc84ada7486e8d1b7: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
